In [1]:
import sys
from pathlib import Path
import os

In [2]:
from modulos.Funciones import *

ruta_proyecto = fr"."
ruta_triangulo = os.path.join(ruta_proyecto, "Data", "generated_monthly_triangles_database.csv")

In [3]:
# Cargamos la base de datos de triángulos
base_triangulo = cargar_base(ruta_triangulo)
base_triangulo.head(10)

,concept,basis,amount_type,level_1,level_2,level_3,accident_period,development_period,amount
0,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-01,0,912.0
1,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-02,0,940.9
2,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-03,0,980.1
3,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-04,0,1010.0
4,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-05,0,1050.6
5,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-06,0,1092.0
6,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-07,0,1144.8
7,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-08,0,1188.0
8,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-09,0,1144.5
9,Exposure,month,cumulative,Auto,Physical Damage,Private Passenger,2016-10,0,1091.8

In [4]:
Triangulo = {}
for concept in base_triangulo["concept"].unique():
    print(f"Concepto: {concept}")
    Triangulo[concept] = convertir_triangulo(base_triangulo, concept=concept)

Triangulo["Loss Incurred"]

Concepto: Exposure
Concepto: Earned Premium
Concepto: Loss Incurred
Concepto: Loss Paid
Concepto: Claims Reported
Concepto: Claims Paid
Concepto: ALAE
Concepto: Salvages
Concepto: Subrogation

development_period,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
accident_period,,,,,,,,,,,,,,,,,,,,,
2016-01,153700.711642,168265.054672,205478.444379,184336.168001,201248.543480,196453.059025,176881.337833,200214.346199,187578.698914,190075.991440,...,177018.978866,171085.713030,173585.908595,169160.747063,173081.527124,176445.361233,172720.085632,173112.466318,174926.788130,175796.196292
2016-02,174526.085249,179397.620865,205041.059805,195258.548978,187048.160649,201436.435289,199293.923502,205210.386921,242546.688042,200341.751962,...,183520.470365,177750.670575,178954.148728,181846.011293,186153.778295,183854.533150,183737.684382,180857.272493,183746.248505,NaN
2016-03,139977.733603,194087.931093,215736.346315,175783.066907,217515.571324,183537.102418,202607.299157,199878.253026,206739.049289,236638.405603,...,185889.013660,185870.257200,187689.323174,188042.155009,189089.878262,185853.845022,186063.868425,184100.501488,NaN,NaN
2016-04,179441.145220,171328.983083,197378.848951,208702.402696,208493.696364,223233.698165,187690.613593,253992.426802,225375.117705,243903.465956,...,200265.915955,199299.153969,197234.175592,195849.823081,193656.903165,201506.058677,196951.796202,NaN,NaN,NaN
2016-05,185553.143033,216977.705207,209628.471276,214214.723923,232801.660391,210101.993900,201936.310336,223423.445555,230653.011303,211583.631794,...,209927.848694,207676.902404,209507.332802,209279.782933,205822.853384,201165.375549,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08,362141.012374,432661.332612,445636.521558,541592.036871,378209.883552,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,367005.573515,415446.207539,433412.965713,518520.051557,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,345630.285842,346963.701868,393892.055949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,393341.831859,322801.177350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12,348148.486210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
base_anual = cambiar_temporalidad(base_triangulo, temporalidad="monthly")
base_anual

     accident_period  development_period       amount
0            2016-01                   0     0.000000
1            2016-01                   1     0.000000
2            2016-01                   2     0.000000
3            2016-01                   3  2420.131387
4            2016-01                   4  5398.637187
...              ...                 ...          ...
7255         2025-10                   1     0.000000
7256         2025-10                   2     0.000000
7257         2025-11                   0     0.000000
7258         2025-11                   1     0.000000
7259         2025-12                   0     0.000000

[7260 rows x 3 columns]

In [6]:
Triangulo_anual = {}
for concept in base_anual  ["concept"].unique():
    print(f"Concepto: {concept}")
    Triangulo_anual[concept] = convertir_triangulo(base_anual, concept=concept)

Triangulo_anual["Loss Incurred"]

KeyError: 'concept'