In [1]:
import sys
from pathlib import Path
import os

In [2]:
from modulos.Funciones import *

ruta_proyecto = fr"."
ruta_triangulo = os.path.join(ruta_proyecto, "Data", "generated_monthly_triangles_database.csv")

# Triángulos LDF

In [3]:
# Cargamos la base de datos de triángulos
base_triangulo = cargar_base(ruta_triangulo)
print(base_triangulo.head(10))

    concept  basis amount_type level_1          level_2            level_3  \
0  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
1  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
2  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
3  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
4  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
5  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
6  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
7  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
8  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger
9  Exposure  month  cumulative    Auto  Physical Damage  Private Passenger

  accident_period  development_period  amount
0         2016-01                   0   912.0
1         2016-02                   0   940.9
2         2016-03                   0   980.1
3         2016-04                   0  1010.0
4         2016-05                   0  1050.6
5         2016-06                   0  1092.0
6         2016-07                   0  1144.8
7         2016-08                   0  1188.0
8         2016-09                   0  1144.5
9         2016-10                   0  1091.8

In [4]:
Triangulo = {}
for concept in base_triangulo["concept"].unique():
    print(f"Concepto: {concept}")
    Triangulo[concept] = convertir_triangulo(base_triangulo, concept=concept)

Triangulo["Loss Incurred"]

Concepto: Exposure
Concepto: Earned Premium
Concepto: Loss Incurred
Concepto: Loss Paid
Concepto: Claims Reported
Concepto: Claims Paid
Concepto: ALAE
Concepto: Salvages
Concepto: Subrogation

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
accident_period,,,,,,,,,,,,,,,,,,,,,
2016-01,153700.711642,168265.054672,205478.444379,184336.168001,201248.543480,196453.059025,176881.337833,200214.346199,187578.698914,190075.991440,...,177018.978866,171085.713030,173585.908595,169160.747063,173081.527124,176445.361233,172720.085632,173112.466318,174926.788130,175796.196292
2016-02,174526.085249,179397.620865,205041.059805,195258.548978,187048.160649,201436.435289,199293.923502,205210.386921,242546.688042,200341.751962,...,183520.470365,177750.670575,178954.148728,181846.011293,186153.778295,183854.533150,183737.684382,180857.272493,183746.248505,NaN
2016-03,139977.733603,194087.931093,215736.346315,175783.066907,217515.571324,183537.102418,202607.299157,199878.253026,206739.049289,236638.405603,...,185889.013660,185870.257200,187689.323174,188042.155009,189089.878262,185853.845022,186063.868425,184100.501488,NaN,NaN
2016-04,179441.145220,171328.983083,197378.848951,208702.402696,208493.696364,223233.698165,187690.613593,253992.426802,225375.117705,243903.465956,...,200265.915955,199299.153969,197234.175592,195849.823081,193656.903165,201506.058677,196951.796202,NaN,NaN,NaN
2016-05,185553.143033,216977.705207,209628.471276,214214.723923,232801.660391,210101.993900,201936.310336,223423.445555,230653.011303,211583.631794,...,209927.848694,207676.902404,209507.332802,209279.782933,205822.853384,201165.375549,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08,362141.012374,432661.332612,445636.521558,541592.036871,378209.883552,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,367005.573515,415446.207539,433412.965713,518520.051557,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,345630.285842,346963.701868,393892.055949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,393341.831859,322801.177350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12,348148.486210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
triangulo_factores = calcular_factores_desarrollo(Triangulo["Loss Incurred"])
triangulo_factores

,0_to_1,1_to_2,2_to_3,3_to_4,4_to_5,5_to_6,6_to_7,7_to_8,8_to_9,9_to_10,...,109_to_110,110_to_111,111_to_112,112_to_113,113_to_114,114_to_115,115_to_116,116_to_117,117_to_118,118_to_119
accident_period,,,,,,,,,,,,,,,,,,,,,
2016-01,1.094758,1.221159,0.897107,1.091747,0.976171,0.900375,1.131913,0.936889,1.013313,1.049322,...,0.996083,0.966482,1.014614,0.974507,1.023178,1.019435,0.978887,1.002272,1.010481,1.00497
2016-02,1.027913,1.142942,0.952290,0.957951,1.076923,0.989364,1.029687,1.181942,0.825993,0.994134,...,0.988735,0.968560,1.006771,1.016160,1.023689,0.987649,0.999364,0.984323,1.015974,NaN
2016-03,1.386563,1.111539,0.814805,1.237409,0.843788,1.103904,0.986530,1.034325,1.144624,0.955552,...,1.011841,0.999899,1.009787,1.001880,1.005572,0.982886,1.001130,0.989448,NaN,NaN
2016-04,0.954792,1.152046,1.057370,0.999000,1.070698,0.840781,1.353251,0.887330,1.082211,0.948795,...,1.008606,0.995173,0.989639,0.992981,0.988803,1.040531,0.977399,NaN,NaN,NaN
2016-05,1.169356,0.966129,1.021878,1.086768,0.902494,0.961135,1.106406,1.032358,0.917324,1.014616,...,1.000932,0.989278,1.008814,0.998914,0.983482,0.977371,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08,1.194732,1.029989,1.215322,0.698330,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,1.131989,1.043247,1.196365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,1.003858,1.135254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,0.820663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Tipo de promedio y número de periodo a considerar

In [6]:
resumen = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="simple",
    ultimos_n=12,
)
resumen.iloc[:12]

               LDF
0_to_1    0.950224
1_to_2    1.084801
2_to_3    1.071894
3_to_4    0.976335
4_to_5    1.011227
5_to_6    1.044487
6_to_7    0.984723
7_to_8    1.108333
8_to_9    0.971907
9_to_10   1.014538
10_to_11  0.980418
11_to_12  1.055502

In [7]:
resumen = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="ponderado",
    ultimos_n=12,
)
resumen.iloc[:12]

               LDF
0_to_1    0.939165
1_to_2    1.078846
2_to_3    1.073926
3_to_4    0.963653
4_to_5    0.998379
5_to_6    1.028142
6_to_7    0.981623
7_to_8    1.092813
8_to_9    0.956561
9_to_10   1.000826
10_to_11  0.978253
11_to_12  1.053080

In [8]:
resumen = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="simple_sin_extremos",
    ultimos_n=12,
)
resumen.iloc[:, :12]

                 LDF
0_to_1      0.948997
1_to_2      1.078430
2_to_3      1.067250
3_to_4      0.985332
4_to_5      0.998466
...              ...
114_to_115  0.996657
115_to_116  0.989126
116_to_117  0.989448
117_to_118  1.013227
118_to_119  1.004970

[119 rows x 1 columns]

# Opcional: desviaciones estándar

In [9]:
simple_desv_2std = resultado = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="simple",
    ultimos_n=12,
    num_std=2
)
simple_desv_2std.iloc[:12]

               LDF
0_to_1    0.950224
1_to_2    1.051996
2_to_3    1.071894
3_to_4    0.983829
4_to_5    0.995763
5_to_6    1.021916
6_to_7    0.984723
7_to_8    1.058062
8_to_9    0.976975
9_to_10   1.034446
10_to_11  0.980418
11_to_12  1.055502

In [10]:
simple_desv_1std = resultado = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="simple",
    ultimos_n=12,
    num_std=2,
    periodos_std = 24
)
simple_desv_1std.iloc[:12]

               LDF
0_to_1    0.959782
1_to_2    1.051996
2_to_3    1.071894
3_to_4    0.983829
4_to_5    0.995763
5_to_6    1.021916
6_to_7    0.950541
7_to_8    1.058062
8_to_9    0.971907
9_to_10   1.034446
10_to_11  0.972010
11_to_12  1.055502

In [11]:
resultado = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="simple_sin_extremos",
    ultimos_n=12,
    num_std=2,
    periodos_std=24,
    excluir_periodos=[2018, 2020],
)
resultado[:12]

               LDF
0_to_1    0.950199
1_to_2    1.053144
2_to_3    1.067250
3_to_4    0.985332
4_to_5    0.998466
5_to_6    1.017116
6_to_7    0.951319
7_to_8    1.066658
8_to_9    0.954675
9_to_10   1.028851
10_to_11  0.969445
11_to_12  1.048597

In [12]:
resultado = seleccionar_ldf(
    triangulo=base_triangulo,
    concept="Loss Incurred",
    metodo="ponderado_sin_extremos",
    ultimos_n=12,
    num_std=2,
    periodos_std=24,
    excluir_celdas=[
        ("2016-01", "0_to_1"),
        ("2019-05", "1_to_2"),
    ],
)

resultado[:12]

               LDF
0_to_1    0.946538
1_to_2    1.048475
2_to_3    1.070606
3_to_4    0.981612
4_to_5    0.993429
5_to_6    1.009345
6_to_7    0.949912
7_to_8    1.063103
8_to_9    0.948216
9_to_10   1.026276
10_to_11  0.965283
11_to_12  1.049573